# Supabase local development configuration

[project]
project_id = "nighttime-story-prep"

[api]
enabled = true
port = 54321
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.buckets.epubs]
public = true
file_size_limit = "50MiB"
allowed_mime_types = ["application/epub+zip"]

[auth]
enabled = false
site_url = "http://localhost:3000"

[edge_runtime]
enabled = false

